[package]
name = "manager-meta"
version = "1.0.0"
authors = ["Micha Vie <micha@peerme.io>", "PeerMe <hello@peerme.io>"]
edition = "2018"
publish = false

[dependencies.manager]
path = ".."

[dependencies.elrond-wasm]
version = "0.37.0"

[dependencies.elrond-wasm-debug]
version = "0.37.0"
