// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           34
// Async Callback (empty):               1
// Total number of exported functions:  36

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    manager
    (
        init => init
        upgrade => upgrade
        addAdmin => add_admin_endpoint
        removeAdmin => remove_admin_endpoint
        forwardToken => forward_token_endpoint
        executeTicket => execute_ticket_endpoint
        createEntity => create_entity_endpoint
        upgradeEntity => upgrade_entity_endpoint
        setFeatures => set_features_endpoint
        setEntityTemplateAddress => set_entity_template_address_endpoint
        setEntityCreationCost => set_entity_creation_cost_endpoint
        getAdmins => admins
        getEntities => entities
        getEntityTemplateAddress => entity_templ_address
        getTrustedHostAddress => trusted_host_address
        getNativeToken => native_token
        getEntityCreationCost => cost_creation_amount
        getFeatures => features
        initCreditsModule => init_credits_module
        setCreditsBonusFactor => set_credits_bonus_factor_endpoint
        setCreditsCostBase => set_credits_cost_base_endpoint
        setCreditsCostExtraPercent => set_credits_cost_extra_percent_endpoint
        setCreditsCostFeature => set_credits_cost_feature_amount_endpoint
        boost => boost_endpoint
        registerExternalBoost => register_external_boost_endpoint
        boostNoReward => boost_no_reward_endpoint
        getCredits => get_credits_view
        getCreditsInfo => get_credits_info_view
        getBaseDailyCost => credits_cost_base_amount
        getBaseExtraPercent => credits_cost_extra_percent
        getCreditsCostFeature => credits_cost_feature_amount
        initDexModule => init_dex_module
        getStableToken => stable_token
        getStablePairContract => stable_token_pair_contract
        initOrgModule => init_organization_module
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
